name: Build aarch64 Darwin

on:
  workflow_call:

jobs:
  build-aarch64-darwin:
    name: Build aarch64 Darwin (static)
    runs-on: namespace-profile-mac-m2-12c28g
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Build the installer
        run: |
          nix build .#packages.aarch64-darwin.nix-installer-static -L
          cp result/bin/nix-installer ./nix-installer-aarch64-darwin
      - name: Create GitHub artifacts from build outputs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: nix-installer-aarch64-darwin
          name: nix-installer-aarch64-darwin
