on:
  workflow_dispatch:
    inputs:
      reference-id:
        type: string
        required: true
      version:
        type: string
        required: true
      determinate-nix-version:
        type: string
        required: true
      upstream-nix-version:
        type: string
        required: true

jobs:
  propose-release:
    uses: DeterminateSystems/propose-release/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "write"
      pull-requests: write
    with:
      reference-id: ${{ inputs.reference-id }}
      version: ${{ inputs.version }}
      extra-commands-early: |
        for fname in $(find ./tests/fixtures -name '*.json'); do
          cat "$fname" \
            | jq '.version = $version' --arg version "${{ inputs.version }}" \
            > "$fname.next"
          mv "$fname.next" "$fname"
          git add "$fname"
        done
        git commit -m "Update test fixtures with the new nix-installer version" || true

        sed -i 's#https://flakehub.com/f/DeterminateSystems/nix-src/=.*";#https://flakehub.com/f/DeterminateSystems/nix-src/=${{ inputs.determinate-nix-version }}";#' ./flake.nix
        sed -i 's#https://releases.nixos.org/nix/nix-.*/nix-.*-";#https://releases.nixos.org/nix/nix-${{ inputs.upstream-nix-version }}/nix-${{ inputs.upstream-nix-version }}-";#' ./flake.nix
        git add flake.nix
        git commit -m "Update Determinate Nix release to ${{ inputs.determinate-nix-version }}" || true
