name: Generate Installer Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      testing_hydra_eval_id:
        description: "Eval ID of Hydra job to use artifacts from for testing"
        required: false
        default: ""

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - name: Create draft release
      # The script also depends on gh and git but those are both pre-installed on the runner
      run: nix run --inputs-from .# nixpkgs#python3 -- assemble_installer.py "${{ github.event.inputs.testing_hydra_eval_id }}"
      env:
        GH_TOKEN: ${{ github.token }}
